# Generated by Django 3.2.6 on 2021-08-28 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuturesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('open_price', models.FloatField(verbose_name='open price')),
                ('close_price', models.FloatField(blank=True, null=True, verbose_name='close price')),
                ('leverage', models.IntegerField(default=1, verbose_name='leverage')),
                ('order_id', models.UUIDField(unique=True, verbose_name='order id')),
                ('side', models.CharField(choices=[('sell', 'Short'), ('buy', 'Long')], max_length=10, null=True, verbose_name='position side')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('logs', models.TextField(blank=True, null=True, verbose_name='logs')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='futures_orders', to='assets.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='futures_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
