version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - .:/app
      - static:/app/static
    command: >
      sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:80"
    environment:
      # - SECRET_KEY=testkey
      # - POSTGRES_DB=app
      # - POSTGRES_USER=postgres
      # - POSTGRES_PASSWORD=supersecretpassword
      - CELERY_USER=admin
      - CELERY_PASS=mypass
      - CELERY_HOST=rabbit
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
      - SECRET_KEY=secretkey
      - CACHE_HOST=localhost
      - DEBUG=True
      - ALLOWED_HOSTS=*
      - TELEGRAM_BOT_TOKEN=1916678554:AAEZCPxzlMvqk9w7FCqF6Z2_mwbPb2wrHec

  telegram-bot:
    build:
      context: .
    # ports:
    #   - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python3 manage.py initiate_telegram_bot"
    environment:
      # - SECRET_KEY=testkey
      # - POSTGRES_DB=app
      # - POSTGRES_USER=postgres
      # - POSTGRES_PASSWORD=supersecretpassword
      - CELERY_USER=admin
      - CELERY_PASS=mypass
      - CELERY_HOST=rabbit
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
      - SECRET_KEY=secretkey
      - CACHE_HOST=localhost
      - DEBUG=True
      - ALLOWED_HOSTS=*
      - TELEGRAM_BOT_TOKEN=1916678554:AAEZCPxzlMvqk9w7FCqF6Z2_mwbPb2wrHec

  cache:
    image: memcached
    ports:
      - "11211:11211"
    entrypoint:
      - memcached
      - -m 64

  # environment:
  #   - DB_HOST=db
  #   - DB_NAME=app
  #   - DB_USER=postgres
  #   - DB_PASS=supersecretpassword
  #   - SECRET_KEY=secretkey
  # depends_on:
  #   - db

  db:
    image: postgres:10-alpine
    restart: on-failure
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword

  # redis:
  #   image: redis:alpine

  rabbit:
    hostname: rabbit
    restart: on-failure
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
      - CELERY_USER=admin
      - CELERY_PASS=mypass
      - CELERY_HOST=rabbit
    ports:
      - "5672:5672"
      - "15672:15672"

  celery:
    # image: celery
    build: .
    restart: always
    command: celery -A plutus worker -l info
    volumes:
      - .:/app
    environment:
      - CELERY_USER=admin
      - CELERY_PASS=mypass
      - CELERY_HOST=rabbit
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
      - SECRET_KEY=secretkey
      - TELEGRAM_BOT_TOKEN=1916678554:AAEZCPxzlMvqk9w7FCqF6Z2_mwbPb2wrHec
    depends_on:
      - db
      - rabbit
      - app

volumes:
  pgdata: {}
  static: {}
