version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    environment:
      # - SECRET_KEY=testkey
      # - POSTGRES_DB=app
      # - POSTGRES_USER=postgres
      # - POSTGRES_PASSWORD=supersecretpassword
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
      - SECRET_KEY=secretkey
      - CACHE_HOST=localhost
      - DEBUG=False
      - ALLOWED_HOSTS=*
      - TELEGRAM_BOT_TOKEN=1916678554:AAEZCPxzlMvqk9w7FCqF6Z2_mwbPb2wrHec

  telegram-bot:
    build:
      context: .
    # ports:
    #   - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python3 manage.py initiate_telegram_bot"
    environment:
      # - SECRET_KEY=testkey
      # - POSTGRES_DB=app
      # - POSTGRES_USER=postgres
      # - POSTGRES_PASSWORD=supersecretpassword
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
      - SECRET_KEY=secretkey
      - CACHE_HOST=localhost
      - DEBUG=False
      - ALLOWED_HOSTS=*
      - TELEGRAM_BOT_TOKEN=1916678554:AAEZCPxzlMvqk9w7FCqF6Z2_mwbPb2wrHec

  cache:
    image: memcached
    ports:
      - "11211:11211"
    entrypoint:
      - memcached
      - -m 64

  # environment:
  #   - DB_HOST=db
  #   - DB_NAME=app
  #   - DB_USER=postgres
  #   - DB_PASS=supersecretpassword
  #   - SECRET_KEY=secretkey
  # depends_on:
  #   - db

  db:
    image: postgres:10-alpine
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword

  redis:
    image: redis:alpine

  celery:
    # image: celery
    build: ./plutus
    restart: always
    command: celery -A plutus worker -l info
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
      - SECRET_KEY=secretkey
      - TELEGRAM_BOT_TOKEN=1916678554:AAEZCPxzlMvqk9w7FCqF6Z2_mwbPb2wrHec
    depends_on:
      - db
      - redis
      - app
