# Generated by Django 3.2.6 on 2021-08-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstrategy',
            name='trade',
            field=models.BooleanField(default=False, verbose_name='trade permission'),
        ),
    ]
