# Generated by Django 3.2.6 on 2021-08-30 13:55

import apps.exchanges.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('symbol', models.CharField(max_length=50, unique=True, verbose_name='symbol')),
                ('ascending_trend', models.BooleanField(default=True, verbose_name='is in an ascending trend?')),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('title', models.CharField(max_length=120, unique=True, verbose_name='title')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.exchanges.models.upload_exchange_logo, verbose_name='logo')),
                ('is_enable', models.BooleanField(default=True, verbose_name='is enable')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeFuturesAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('code_name', models.CharField(max_length=50, verbose_name='code name')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_futures_assets', to='exchanges.asset')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_futures_assets', to='exchanges.exchange')),
            ],
            options={
                'unique_together': {('exchange', 'asset', 'code_name')},
            },
        ),
        migrations.AddField(
            model_name='exchange',
            name='futures_assets',
            field=models.ManyToManyField(related_name='exchanges', through='exchanges.ExchangeFuturesAsset', to='exchanges.Asset'),
        ),
    ]
