# Generated by Django 3.2.6 on 2021-08-28 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('symbol', models.CharField(max_length=50, verbose_name='symbol')),
                ('pair', models.CharField(max_length=50, verbose_name='pair')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='price')),
                ('code_name', models.CharField(max_length=120, verbose_name='code name')),
                ('exchange', models.CharField(choices=[('kucoin', 'Kucoin'), ('aax', 'Aax')], default='aax', max_length=120, verbose_name='exchange')),
                ('ascending_trend', models.BooleanField(default=True, verbose_name='is in an ascending trend?')),
            ],
            options={
                'unique_together': {('code_name', 'exchange')},
            },
        ),
    ]
