# Generated by Django 3.2.6 on 2021-08-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='last name')),
                ('username', models.CharField(max_length=120, unique=True, verbose_name='last name')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='user id')),
                ('is_enable', models.BooleanField(default=True, verbose_name='is enable?')),
            ],
        ),
    ]
